-- Seed dedicated E2E test users.
--
-- Plaintext password for BOTH accounts: e2e-pass-123
--
-- The password hash is generated by PostgreSQL's pgcrypto extension using the
-- Blowfish (bcrypt) scheme: gen_salt('bf', 12) produces a $2a$12$... hash that
-- is fully compatible with Go's golang.org/x/crypto/bcrypt verification.
-- pgcrypto is already enabled by migration 001_initial.up.sql.
--
-- ON CONFLICT keeps the script idempotent: re-running it refreshes the password
-- and re-activates the accounts so the smoke test stays repeatable.

INSERT INTO users (username, display_name, password_hash, role)
VALUES
  ('teacher_test', 'E2E 先生', crypt('e2e-pass-123', gen_salt('bf', 12)), 'teacher'),
  ('student_test', 'E2E 生徒', crypt('e2e-pass-123', gen_salt('bf', 12)), 'student')
ON CONFLICT (username) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      display_name  = EXCLUDED.display_name,
      role          = EXCLUDED.role,
      is_active     = TRUE,
      deleted_at    = NULL,
      updated_at    = NOW();
